SELECT TOP (1000) [ID]
      ,[First_Day]
      ,[Second_Day]
      ,[Third_Day]
      ,[Fourth_Day]
      ,[Fifth_Day]
      ,[Sixth_Day]
      ,[Seventh_Day]
      ,[Total_Average]
  FROM [SoftwareDevelopmentCalorieTracker].[dbo].[CalorieTracker]
